### ISSUE TITLE
Add support for gitlab pages?

### ISSUE THREAD

**Issue by nrinaudo** [sbt/sbt-ghpages#28]
Gitlab pages are slightly less straightforward than Github pages, but a working integration for Scala could be:

- have a special branch called `gl-pages` mirror the behaviour of `gh-pages` for Github
- store permanently a `.gitlab-ci.yml` file in that branch

For example, for jekyll:

```yml
image: ruby:2.3

pages:
  script:
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
```

In order for this workflow to be supported by `sbt-ghpages`, we'd need very little:
- make the name of the git branch configurable (defaulting to `gh-pages`).
- add a setting that lets us control which files are ignored when cleaning the content of the special git branch before publishing (defaulting to `None`).

I'd be happy to try and put a PR together if this is deemed interesting.
